In [1]:
import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수',
            '최지은', '정하늘', '강민호'],
    '과목': ['Python', 'Python', 'Java',
            'Java', 'Python', 'Java'],
    '점수': [85, 92, 78, 88, 76, 95]
})
df

    이름      과목  점수
0  김철수  Python  85
1  이영희  Python  92
2  박민수    Java  78
3  최지은    Java  88
4  정하늘  Python  76
5  강민호    Java  95

### 오늘의 문제
과목별 평균 점수를 구하고, 평균이 높은 과목부터 내림차순으로 출력하세요.
가능하면 다음 세 가지 조건도 만족하도록 작성해 보세요.
- groupby()를 사용할 것
- 평균 점수의 열 이름을 평균점수로 지정할 것
- 결과를 DataFrame 형태로 출력할 것

In [ ]:
result = df.groupby('과목')['점수'].mean().reset_index(name="평균점수").sort_values("평균점수", ascending=False)
result

       과목       평균점수
0    Java  87.000000
1  Python  84.333333

### 같은 데이터에서 80점 이상인 학생만 선택한 다음 과목별 평균 점수를 구해 보세요.

In [10]:
df[df['점수'] >= 80].groupby('과목')['점수'].mean().reset_index(name="평균점수").sort_values("평균점수", ascending=False)

       과목  평균점수
0    Java  91.5
1  Python  88.5